{
 "title": "Test llm models",
 "time": { "from": "2023-12-17T19:06:08.626Z", "to": "2023-12-17T19:30:07.540Z" },
 "panels": [
  {
   "title": "Correct and total answers",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (model) (correct_answer{job=\"llm\"})",
     "legendFormat": "{{model}}"
    },
    {
     "expr": "max by (job) (total_answer{job=\"llm\"})",
     "legendFormat": "Total question"
    }
   ]
  },
  {
   "title": "Tokens in response",
   "type": "bargauge",
   "description": "number of tokens in the response",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (model,subquery) (eval_count)",
     "legendFormat": "{{model}} {{subquery}}"
    }
   ]
  },
  {
   "title": "Total duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model) (total_duration)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens in prompt",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (model,subquery) (prompt_eval_count)",
     "legendFormat": "{{model}} {{subquery}}"
    }
   ]
  }
 ]
}