k8s -> cartography -> neo4j
user <-> langchain <-> llm
langchain <-> neo4j
user: {shape: image
icon: https://icons.terrastruct.com/essentials%2F365-user.svg}
llm: {shape: image
icon: https://icons.terrastruct.com/essentials%2F092-network.svg}
k8s: {shape: image
 icon: https://www.vectorlogo.zone/logos/kubernetes/kubernetes-icon.svg}
cartography: {shape: image
 icon: https://lyft.github.io/cartography/_static/logo-vertical.svg}
neo4j: { shape: image
  icon: https://www.vectorlogo.zone/logos/neo4j/neo4j-icon.svg}